[package]
name = "automatea"
version = "0.1.0"
authors = ["mbenoukaiss <marwane.benou-kaiss@etu.u-bordeaux.fr>"]
edition = "2018"

[dependencies]
automatea-proc = { path = "proc" }
reqwest = "0.9.19"
ws = { version = "0.9.0", features = ["ssl"] }
url = "2.1.0"
chrono = "0.4.7"
log = "0.4.8"
fern = "0.5.8"
backtrace = "0.3.37"

[dev-dependencies]
serde_json = "1.0.40"
serde = "1.0.98"

[features]
default = []

# Removes some checks that are not necessary
squeeze_performance = []

# Checks for unused fields when deserializing an object.
# Should only be used in development to make sure no field
# was forgotten as it slows down the deserializer.
strict_deserializer = []

# Shows backtrace when
json_backtrace = []