[package]
name = "automatea"
version = "0.1.0"
authors = ["mbenoukaiss <marwane.benou-kaiss@etu.u-bordeaux.fr>"]
edition = "2018"

[dependencies]
automatea-proc = { path = "proc" }
tokio = "0.2.0-alpha.6"
hyper = { version = "0.13.0-alpha.4", features = ["unstable-stream"] }
hyper-tls = "0.4.0-alpha.4"
futures-preview = { version = "0.3.0-alpha.19", features = ["compat"] }
ws = { version = "0.9.1", features = ["ssl"] }
chrono = "0.4.9"
log = "0.4.8"
backtrace = "0.3.40"

[dev-dependencies]
serde = { version = "1.0.101", features = ["derive"]}
serde_json = "1.0.41"

[features]
default = []

# Removes some checks that are not necessary
squeeze_performance = []

# Checks for unused fields when deserializing an object.
# Should only be used in development to make sure no field
# was forgotten as it slows down the deserializer.
strict_deserializer = []
