[package]
name = "automate"
version = "0.1.4"
authors = ["mbenoukaiss <marwane.benou-kaiss@etu.u-bordeaux.fr>"]
license = "MIT"
repository = "https://github.com/mbenoukaiss/automate"
keywords = ["discord", "api", "async"]
categories = ["api-bindings"]
description = "An asynchronous library to interact with Discord API"
readme = "README.md"
edition = "2018"

[dependencies]
automate-derive = { version = "0.1.4", path = "derive" }
futures = "0.3"
async-trait = "0.1"
tokio = "0.2"
hyper = "0.13"
hyper-tls = "0.4"
ws = { version = "0.9.1", features = ["ssl"] }
chrono = "0.4"
log = "0.4"
percent-encoding = "2.1.0"

[dependencies.backtrace]
version = "0.3.40"
optional = true

[dev-dependencies]
serde = { version = "1.0.103", features = ["derive"]}
serde_json = "1.0.42"

[features]
default = []

# Checks for unused fields when deserializing an object.
strict-deserializer = []
