[package]
name = "automatea"
version = "0.1.0"
authors = ["mbenoukaiss <marwane.benou-kaiss@etu.u-bordeaux.fr>"]
edition = "2018"

[dependencies]
automatea-proc = { path = "proc" }
reqwest = "0.9.19"
ws = { version = "0.9.0", features = ["ssl"] }
serde_json = "1.0.40"
serde = "1.0.98"
chrono = "0.4.7"
log = "0.4.8"
fern = "0.5.8"

[features]
default = []
squeeze_performance = []