[package]
name = "automatea-proc"
version = "0.1.0"
authors = ["mbenoukaiss <marwane.benou-kaiss@etu.u-bordeaux.fr>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.1"
syn = { version = "1.0.3", features = ["extra-traits"]}
quote = "1.0.2"
