name: Benchmark
on:
  schedule:
    - cron: 0 0 1 * *

jobs:
  bench:
    name: Bench
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install toolchain
        uses: actions-rs/toolchain@master
        with:
          toolchain: nightly
          override: true
      - name: Run benchmark
        uses: actions-rs/cargo@master
        with:
          command: bench
          args: --all-targets
