# This repository currently requires nightly.
# in order to know which nightly can be used,
# this website tells for which nightly versions
# clippy and other tools are available :
#
# https://rust-lang.github.io/rustup-components-history

name: Benchmark
on:
  schedule:
    - cron: 0 0 1 * *

jobs:
  bench:
    name: Bench
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install toolchain
        uses: actions-rs/toolchain@master
        with:
          toolchain: 1.40.0-nightly
          override: true
      - name: Run benchmark
        uses: actions-rs/cargo@master
        with:
          command: bench
          args: --all-targets
