# This repository currently requires nightly.
# in order to know which nightly can be used,
# this website tells for which nightly versions
# clippy and other tools are available :
#
# https://rust-lang.github.io/rustup-components-history

name: Checks
on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install toolchain with clippy
        uses: actions-rs/toolchain@master
        with:
          profile: minimal
          toolchain: nightly-2020-01-31
          components: clippy
          override: true
      - name: Run clippy
        uses: actions-rs/cargo@master
        with:
          command: clippy
          args: -- -D warnings

  test:
    name: Tests
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
      - name: Install toolchain
        uses: actions-rs/toolchain@master
        with:
          profile: minimal
          toolchain: nightly-2020-01-31
          override: true
      - name: Run tests
        uses: actions-rs/cargo@master
        with:
          command: test
          args: --all-targets
